name: create new branch

on:
  repository_dispatch:
    types: [create]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: ruby setup
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6  
      - name: checkout dev
        uses: actions/checkout@v2
        with:
          ref: dev

      - name: Create new Branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pwd
          ls
          ruby ./modifyAmplify.rb ${{github.event.client_payload.reactEnv}}
          git switch -c ${{ github.event.client_payload.ref }}
          git push origin ${{ github.event.client_payload.ref }}
